### ISSUE TITLE
영문페이지 헤더 표시 오류

### ISSUE THREAD

**Issue by miriryu** [femiwiki/FemiwikiSkin#116]
영문페이지에서 헤더의 [Recent Changes] 버튼과 [Random Pages] 버튼 텍스트가 다음줄로 밀려나서 표시됨

![image](https://user-images.githubusercontent.com/41344968/71607263-d4bb3d80-2b45-11ea-9ab0-8c65cbb9e496.png)

**Comment by lens0021** [comment]
> 생각해보니 영어페이지 말고 다른 제 3의 언어도 있을 수 있어서
> 걍 페이지 언어가 뭐든간에 다 통하는 해결책을 쓰는게 맞을거같네용
> -- simnalamburt , https://discordapp.com/channels/314953743185477644/566264019409698817/661388345078841357

한국어의 경우도 따로 수정 안 하면 아래와 같이 나타납니다.
![image](https://user-images.githubusercontent.com/28209361/71616086-cc233f80-2bf7-11ea-8ba2-3a3da56ec5fb.png)
