### ISSUE TITLE
[Safari] 문서의 분류 목록이 이상한 곳에서 줄바꿈이 되는 현상

### ISSUE THREAD

**Issue by Larodi** [femiwiki/FemiwikiSkin#152]
- 접음
<img width="808" alt="image" src="https://user-images.githubusercontent.com/67490628/85911463-5a534800-b860-11ea-9d55-5bb2fa129110.png">

- 펼침
<img width="806" alt="image" src="https://user-images.githubusercontent.com/67490628/85911414-14967f80-b860-11ea-848d-6ba03b3f8e6f.png">

문서 하단 분류 목록에서 줄바꿈이 알 수 없는 곳에서 됨.
분류를 펼쳐 상위분류를 확인하면 맨 윗줄이 아래로 내려감.

**Comment by lens0021** [comment]
패치 https://github.com/femiwiki/FemiwikiSkin/commit/36727a5bcf8ef41ce30470a2c0277f2230a0ee87 적용되었으며 같은 증상이 계속되면 여기 남겨주세요 :smile:
