### ISSUE TITLE
mediawiki.skinning.content.externallinks is deprecated

### ISSUE THREAD

**Issue by jdlrobson** [femiwiki/FemiwikiSkin#210]
The `mediawiki.skinning.content.externallinks` module is deprecated.

[Impacted skins](https://codesearch.wmcloud.org/search/?q=content.externallinks&i=nope&files=&repos=) should use ResourceLoaderSkinModule following the example in [Monobook](https://gerrit.wikimedia.org/r/c/mediawiki/skins/MonoBook/+/645453)

If no action is taken the module will eventually be removed and styles for icons that show up against links will no longer function in the skin.

**Comment by simnalamburt** [comment]
Thanks for letting us know this issue!
