### ISSUE TITLE
Add branch for REL1_36

### ISSUE THREAD

**Issue by RhinosF1** [femiwiki/FemiwikiSkin#216]
All extensions should now be branched.

**Comment by lens0021** [comment]
ToDo list (All extensions of FemiWiki):

- [ ] [AchievementBadges]
- [ ] [DiscordNotifications]
- [ ] [FacetedCategory]
- [ ] [FemiwikiSkin]
- [ ] [Sanctions]
- [ ] [UnifiedExtensionForFemiwiki]

[achievementbadges]: https://github.com/femiwiki/AchievementBadges
[categoryintersectionsearch]: https://github.com/femiwiki/CategoryIntersectionSearch
[discordnotifications]: https://github.com/femiwiki/discordnotifications
[facetedcategory]: https://github.com/femiwiki/FacetedCategory
[femiwikiskin]: https://github.com/femiwiki/FemiwikiSkin
[sanctions]: https://github.com/femiwiki/Sanctions
[unifiedextensionforfemiwiki]: https://github.com/femiwiki/UnifiedExtensionForFemiwiki

**Comment by lens0021** [comment]
Branched and tests against MW 1.36 are passed[1], Thanks!

[1] https://github.com/femiwiki/FemiwikiSkin/runs/2304110164?check_suite_focus=true
