### ISSUE TITLE
Fatal error on 1.36

### ISSUE THREAD

**Issue by Universal-Omega** [femiwiki/FemiwikiSkin#263]
We get:
```
Argument 2 passed to MediaWiki\Skins\Femiwiki\SkinFemiwiki::getPortletData() must be of the type array, string given, called in /srv/mediawiki/w/skins/Femiwiki/includes/SkinFemiwiki.php on line 87
```
With 1.36.0

**Comment by lens0021** [comment]
I could add a conditional statement to make only an array be passed to `getPortletData() `... But it will be helpful if I know what is the content of `MediaWiki:Sidebar` which invoked that error.

Could you give me a link to the wiki where the error occuerred, or copy-paste the content of `MediaWiki:Sidebar` If the wiki is not a public wiki?

**Comment by Universal-Omega** [comment]
> I could add a conditional statement to make only an array be passed to `getPortletData() `... But it will be helpful if I know what is the content of `MediaWiki:Sidebar` which invoked that error.
> 
> Could you give me a link to the wiki where the error occuerred, or copy-paste the content of `MediaWiki:Sidebar` If the wiki is not a public wiki?

https://test3.miraheze.org but I reverted the update after the error occured.

**Comment by lens0021** [comment]
[Extension:AddThis](https://www.mediawiki.org/wiki/Extension:AddThis) was the cause of the error and I have tested the above commit solve the issue.

**Comment by lens0021** [comment]
the [v1.7.4](https://github.com/femiwiki/FemiwikiSkin/releases/tag/v1.7.4) release includes the patch of this. could you test it again, @Universal-Omega?

**Comment by Universal-Omega** [comment]
It would appear to work. Thank you!
