### ISSUE TITLE
Notice: Undefined index: id for language links

### ISSUE THREAD

**Issue by jdlrobson** [femiwiki/FemiwikiSkin#297]
Noticing ( ! ) Notice: Undefined index: id in /vagrant/mediawiki/skins/Femiwiki/includes/SkinFemiwiki.php on line 195
Call Stack on a wiki

The issue is `$id = $item['id']`

This is possible for some links e.g. language links

You can either fix it with:
```
			$id = $item['id'] ?? $name . '-item-' . $key;
```
(patch incoming)

OR
```

			$id = $item['id'];
			if ( $id && isset( $xeIconMap[$id] ) ) {
```

**Comment by lens0021** [comment]
yeah, the former which your PR implements seems to be better for me, too.
