### ISSUE TITLE
Set Skin::VERSION_MAJOR to 2

### ISSUE THREAD

**Issue by lens0021** [femiwiki/FemiwikiSkin#462]
https://github.com/wikimedia/mediawiki/blob/REL1_37/includes/skins/Skin.php#L74-L75

https://github.com/wikimedia/mediawiki/blob/REL1_37/includes/skins/Skin.php#L79-L88

**Comment by jdlrobson** [comment]
Can you elaborate on what Femiwiki plans to do here?

The VERSION_MAJOR is meant for large scale changes in the getTemplateData specification. No plan to use it just yet.

**Comment by lens0021** [comment]
I thought it is related to the native support to dismiss sitenotice in the core. Then, will it be available in the future?

**Comment by jdlrobson** [comment]
Unfortunately sitenotice dismiss functionality never made it into core (got reverted).

More information at https://phabricator.wikimedia.org/T259903
