### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/FemiwikiSkin#64]
- [x] Remove unused files &rarr; b8c3ae0
- [x] Commit Lockfiles &rarr; 8e5344c, d73226d
- [x] Normalize indentations styles &rarr; 523100b
- [x] Update composer dependencies &rarr; 3699a1c
- [x] CI &rarr; 1e395e8
- [x] Use phpcs &rarr; 986432a
- [x] Update npm dependencies &rarr; 5e38fe2
- [x] Replace jshint with prettier &rarr; 096b544, c038c5e
- [x] Add prettier to CI &rarr; 1001f06
- [x] Get rid of grunt &rarr; 1001f06
- [x] Bundle normalize.css &rarr; 98f60b4
- [ ] #502
- [ ] (Optional) less to scss
- Get rid of jQuery &rarr; https://github.com/femiwiki/FemiwikiSkin/issues/261

**Comment by lens0021** [comment]
항목이 매우 적게 남아 이 이슈는 닫겠습니다
